# Generated by Django 2.2 on 2019-04-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('reper', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sku']},
        ),
    ]
