# Generated by Django 2.2 on 2019-04-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20190411_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['sku'], 'verbose_name': '中古手机', 'verbose_name_plural': '中古手机'},
        ),
    ]
